use_frameworks!

platform :ios, '9.0'

target 'Analytically_Example' do
#  pod 'Analytically', :path => '../'
  pod 'Analytically/Flurry', :path => '../'

  target 'Analytically_Tests' do
    inherit! :search_paths

    
  end
end
